-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-05 16:08:46 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Klient 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     imie VARCHAR (60) NOT NULL , 
     nazwisko VARCHAR (60) NOT NULL , 
     data_urodzin DATE NOT NULL , 
     numer_karty_kredytowej VARCHAR (60) NOT NULL , 
     email VARCHAR (60) , 
     numer_telefonu VARCHAR (45) , 
     Lokalizacja_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Klient ADD CONSTRAINT Klient_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Lokalizacja 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     ulica VARCHAR (60) NOT NULL , 
     miasto VARCHAR (60) NOT NULL , 
     kraj VARCHAR (60) NOT NULL , 
     kod_pocztowy VARCHAR (10) NOT NULL , 
     numer_domu VARCHAR (5) NOT NULL 
    )
GO

ALTER TABLE Lokalizacja ADD CONSTRAINT Lokalizacja_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Pracownik 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     imie VARCHAR (60) NOT NULL , 
     nazwisko VARCHAR (60) NOT NULL , 
     data_urodzin DATE NOT NULL , 
     stanowisko VARCHAR (60) NOT NULL , 
     data_zatrudnienia DATE NOT NULL , 
     pensja INTEGER , 
     email VARCHAR (60) , 
     numer_telefonu VARCHAR (45) , 
     Lokalizacja_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Pracownik ADD CONSTRAINT Pracownik_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Rodzaj_Platnosci 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     nazwa VARCHAR (45) NOT NULL 
    )
GO

ALTER TABLE Rodzaj_Platnosci ADD CONSTRAINT Rodzaj_Platnosci_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Samochod 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     marka VARCHAR (60) NOT NULL , 
     model VARCHAR (60) NOT NULL , 
     przebieg INTEGER NOT NULL , 
     rok_produkcji DATE NOT NULL , 
     pojemnosc_silnika INTEGER NOT NULL , 
     numer_rejestracyjny VARCHAR (11) NOT NULL , 
     dostepnosc CHAR (1) NOT NULL , 
     kolor VARCHAR (60) , 
     ilosc_siedzen INTEGER , 
     Samochod_Kategoria_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Samochod ADD CONSTRAINT Samochod_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Samochod_Kategoria 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     nazwa VARCHAR (45) NOT NULL , 
     cena_za_dzien FLOAT NOT NULL , 
     cena_za_godzine FLOAT 
    )
GO

ALTER TABLE Samochod_Kategoria ADD CONSTRAINT Samochod_Kategoria_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Wypozyczenie 
    (
     id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     data_pocz¹tku_wypozyczenia DATE NOT NULL , 
     data_konca_wypozyczenia DATE NOT NULL , 
     kwota_platnosci NUMERIC (28) NOT NULL , 
     stan_licznika_przed FLOAT NOT NULL , 
     Samochod_id INTEGER NOT NULL , 
     Klient_id INTEGER NOT NULL , 
     Pracownik_id INTEGER NOT NULL , 
     Lokalizacja_wypozyczenia_id INTEGER NOT NULL , 
     Lokalizacja_oddania_id INTEGER NOT NULL , 
     Rodzaj_Platnosci_id INTEGER 
    )
GO

ALTER TABLE Wypozyczenie ADD CONSTRAINT Wypozyczenie_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Klient 
    ADD CONSTRAINT Klient_Lokalizacja_FK FOREIGN KEY 
    ( 
     Lokalizacja_id
    ) 
    REFERENCES Lokalizacja 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Pracownik 
    ADD CONSTRAINT Pracownik_Lokalizacja_FK FOREIGN KEY 
    ( 
     Lokalizacja_id
    ) 
    REFERENCES Lokalizacja 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Samochod 
    ADD CONSTRAINT Samochod_Samochod_Kategoria_FK FOREIGN KEY 
    ( 
     Samochod_Kategoria_id
    ) 
    REFERENCES Samochod_Kategoria 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Wypozyczenie 
    ADD CONSTRAINT Wypozyczenie_Klient_FK FOREIGN KEY 
    ( 
     Klient_id
    ) 
    REFERENCES Klient 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Wypozyczenie 
    ADD CONSTRAINT Wypozyczenie_Lokalizacja_FK FOREIGN KEY 
    ( 
     Lokalizacja_oddania_id
    ) 
    REFERENCES Lokalizacja 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Wypozyczenie 
    ADD CONSTRAINT Wypozyczenie_Lokalizacja_FKv2 FOREIGN KEY 
    ( 
     Lokalizacja_wypozyczenia_id
    ) 
    REFERENCES Lokalizacja 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Wypozyczenie 
    ADD CONSTRAINT Wypozyczenie_Pracownik_FK FOREIGN KEY 
    ( 
     Pracownik_id
    ) 
    REFERENCES Pracownik 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Wypozyczenie 
    ADD CONSTRAINT Wypozyczenie_Rodzaj_Platnosci_FK FOREIGN KEY 
    ( 
     Rodzaj_Platnosci_id
    ) 
    REFERENCES Rodzaj_Platnosci 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Wypozyczenie 
    ADD CONSTRAINT Wypozyczenie_Samochod_FK FOREIGN KEY 
    ( 
     Samochod_id
    ) 
    REFERENCES Samochod 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
